// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKO-j4pzTz0WG3gTjXqlzhuzIKGfhH9Xs',
    appId: '1:789989064483:web:8ee6f10bf74d76cda09696',
    messagingSenderId: '789989064483',
    projectId: 'rescue-b09eb',
    authDomain: 'rescue-b09eb.firebaseapp.com',
    storageBucket: 'rescue-b09eb.appspot.com',
    measurementId: 'G-6R26FHB02C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZAl-p1bKDAM3ooZWwfsccWb5hG3d91xs',
    appId: '1:789989064483:android:be588102a53a7147a09696',
    messagingSenderId: '789989064483',
    projectId: 'rescue-b09eb',
    storageBucket: 'rescue-b09eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnW9AXKeMPs6hCig2Rg5wNIfPm0VKU21M',
    appId: '1:789989064483:ios:86e30c94d2b08173a09696',
    messagingSenderId: '789989064483',
    projectId: 'rescue-b09eb',
    storageBucket: 'rescue-b09eb.appspot.com',
    iosClientId:
        '789989064483-teqhrglpepelegtenqhabbrqktidme8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.rescue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnW9AXKeMPs6hCig2Rg5wNIfPm0VKU21M',
    appId: '1:789989064483:ios:86e30c94d2b08173a09696',
    messagingSenderId: '789989064483',
    projectId: 'rescue-b09eb',
    storageBucket: 'rescue-b09eb.appspot.com',
    iosClientId:
        '789989064483-teqhrglpepelegtenqhabbrqktidme8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.rescue',
  );
}
